Settings load successfuly with arguments: ['1', 'BM']
Traceback (most recent call last):
  File "/home/jupiter/Rychara_Silver/main.py", line 122, in <module>
    asyncio.run(main(sys.argv[1:]))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/jupiter/Rychara_Silver/main.py", line 111, in main
    time.sleep(1)
KeyboardInterrupt
